spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sureme?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

  redis:
      host: 127.0.0.1
      password: root
      port: 6379
      pool.maxIdle: 8
      pool.minIdle: 0
      database: 6

image:
  path: /data2/html/sureme/build/image
  host:

wx:
  app-id:
  app-secret: