spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sureme?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

  redis:
    host: 127.0.0.1
    password: q7FIqKnrILC98sTeb2Z2
    port: 6380

image:
  path: /data2/html/sureme/build/image
  host:

wx:
  app-id:
  app-secret: