
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
#        strategy: org.hibernate.cfg.ImprovedNamingStrategy
        implicit-strategy: top.xuguoliang.common.config.CustomNamingStrategy
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/sureme?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    tomcat:
      test-while-idle: true
      max-active: 3
      initial-size: 1


  redis:
    host: 127.0.0.1
    password: root
    port: 6379
    pool.maxIdle: 8
    pool.minIdle: 0
    database: 5
  messages.basename: messages
  jackson:
    default-property-inclusion: always


qiniu:
  access-key: ce9a-vgseoe6rtFL1H2EvNPy9xtcnGxhsQMYznAX
  bucket: sureme
  link-address: https://img.suremeshop.com/
  secret-key: hoH2iv8taGgDlmc708bTqUJDJiMbck7pw7xg2OVL


image:
  path: /data2/html/sureme/build/image
  host:

wx:
  url: https://api.weixin.qq.com/sns/jscode2session
  app-id: wx03b5a6bfb046b8c3
  app-secret: 6b61574dbaff3684dd5c4b0c43e4a720

# 微信支付
wechat:
  pay:
    appId: wx03b5a6bfb046b8c3
    mchId: 1489511922
    mchKey: 0358ADC84FAA8EF8037815882EA075AD
    keyPath: classpath:apiclient_cert.p12
# 微信相关日志
logging:
  level:
    com.github.binarywang.demo.wx.pay: DEBUG
    com.github.binarywang.wxpay: DEBUG


game.apiKey: 0com19AKhMMIhBC5BDb78eVJkTCwBDSK
game.apiSecret: XDCeR1tYFE-EYNTiCKwFIV-AXajU4Pup